export type RestaurantMenuItem = {
  id: number;
  name: string;
  category: string;
  description: string | null;
  pricePkr: number;
  imageUrl: string | null;
  isFeatured: boolean;
};

// Curated from Saltanat's current public menu. Confirm prices with the restaurant
// before ordering; the published menu may change.
export const restaurantMenu: RestaurantMenuItem[] = [
  {
    id: 1,
    name: "Honey Mustard Wings",
    category: "Starters",
    description: "Crispy wings tossed in honey mustard sauce, served with fries.",
    pricePkr: 999,
    imageUrl: "/brand/honey-wings.jpg",
    isFeatured: true,
  },
  {
    id: 2,
    name: "Saltanat Special Wings",
    category: "Starters",
    description: "Eight pieces from the restaurant's signature wings selection.",
    pricePkr: 1099,
    imageUrl: "/brand/honey-wings.jpg",
    isFeatured: false,
  },
  {
    id: 3,
    name: "Mexican Wings",
    category: "Starters",
    description: "Fried wings tossed in spicy Mexican sauce, served with fries.",
    pricePkr: 999,
    imageUrl: "/brand/honey-wings.jpg",
    isFeatured: false,
  },
  {
    id: 4,
    name: "Saltanat Special Prawns",
    category: "Seafood",
    description: "Eight prawns marinated with Saltanat's special sauce.",
    pricePkr: 2399,
    imageUrl: null,
    isFeatured: true,
  },
  {
    id: 5,
    name: "Chicken Corn Soup",
    category: "Soup & Salad",
    description: "Chicken stock with minced chicken and sweet corn.",
    pricePkr: 449,
    imageUrl: null,
    isFeatured: false,
  },
  {
    id: 6,
    name: "Fresh Garden Salad",
    category: "Soup & Salad",
    description: "A fresh garden salad.",
    pricePkr: 379,
    imageUrl: null,
    isFeatured: false,
  },
  {
    id: 7,
    name: "Chicken Bihari Boti",
    category: "BBQ & Grills",
    description: "A classic Bihari-style barbecue favourite.",
    pricePkr: 1549,
    imageUrl: "/brand/tawa-chicken.jpg",
    isFeatured: false,
  },
  {
    id: 8,
    name: "Beef Bihari Boti",
    category: "BBQ & Grills",
    description: "Beef Bihari boti, cooked over charcoal.",
    pricePkr: 1699,
    imageUrl: "/brand/tawa-chicken.jpg",
    isFeatured: false,
  },
  {
    id: 9,
    name: "Chicken Tandoori Boti",
    category: "BBQ & Grills",
    description: "Bone-in chicken marinated with ginger, garlic and red chilli.",
    pricePkr: 1549,
    imageUrl: "/brand/tawa-chicken.jpg",
    isFeatured: true,
  },
  {
    id: 10,
    name: "Fish Tikka",
    category: "BBQ & Grills",
    description: "Fish cubes marinated in traditional tikka masala and charcoal cooked.",
    pricePkr: 1999,
    imageUrl: null,
    isFeatured: false,
  },
  {
    id: 11,
    name: "Shahi Chicken Namkeen Karahi",
    category: "Karahi & Handi",
    description: "Full portion, made in butter with a savoury spice blend.",
    pricePkr: 3299,
    imageUrl: "/brand/tawa-chicken.jpg",
    isFeatured: true,
  },
  {
    id: 12,
    name: "Chicken White Karahi",
    category: "Karahi & Handi",
    description: "A creamy chicken karahi from the current menu.",
    pricePkr: 3449,
    imageUrl: "/brand/tawa-chicken.jpg",
    isFeatured: false,
  },
  {
    id: 13,
    name: "Peshawari Chicken Karahi",
    category: "Karahi & Handi",
    description: "Full portion with a tomato-based Peshawari gravy.",
    pricePkr: 3349,
    imageUrl: "/brand/tawa-chicken.jpg",
    isFeatured: false,
  },
  {
    id: 14,
    name: "Tawa Chicken",
    category: "Tawa Specials",
    description: "A sizzling chicken special from the tawa menu.",
    pricePkr: 1299,
    imageUrl: "/brand/tawa-chicken.jpg",
    isFeatured: true,
  },
  {
    id: 15,
    name: "Mutton Katakat",
    category: "Tawa Specials",
    description: "Tawa-fried kidney, heart and brain with butter and house spices.",
    pricePkr: 2599,
    imageUrl: null,
    isFeatured: false,
  },
  {
    id: 16,
    name: "Shahi Mutton Turkish Kabab",
    category: "BBQ & Grills",
    description: "A Turkish-style mutton kabab from the shahi selection.",
    pricePkr: 1549,
    imageUrl: null,
    isFeatured: false,
  },
  {
    id: 17,
    name: "Grilled Platter",
    category: "Family Platters",
    description: "A sharing platter from Saltanat's grilled selection.",
    pricePkr: 5499,
    imageUrl: "/brand/tawa-chicken.jpg",
    isFeatured: true,
  },
  {
    id: 18,
    name: "Special Family Platter",
    category: "Family Platters",
    description: "Serves 6–7; includes mutton ribs, chicken cheese kabab and more.",
    pricePkr: 18999,
    imageUrl: "/brand/tawa-chicken.jpg",
    isFeatured: true,
  },
  {
    id: 19,
    name: "Classic Mushroom Beef Burger",
    category: "Burgers",
    description: "A beef burger with mushroom and Swiss cheese.",
    pricePkr: 1099,
    imageUrl: "/brand/burger.jpg",
    isFeatured: false,
  },
  {
    id: 20,
    name: "Slice of Three Milk Cake",
    category: "Desserts & Drinks",
    description: "A slice of three milk cake.",
    pricePkr: 699,
    imageUrl: null,
    isFeatured: false,
  },
  {
    id: 21,
    name: "Saltanat Special Kahwa",
    category: "Desserts & Drinks",
    description: "Saltanat's special kahwa.",
    pricePkr: 279,
    imageUrl: null,
    isFeatured: false,
  },
];