CREATE TABLE IF NOT EXISTS restaurant_reservation_requests (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    phone text NOT NULL,
    preferred_date date NOT NULL,
    preferred_time text NOT NULL,
    guest_count integer NOT NULL,
    notes text,
    status text NOT NULL DEFAULT 'awaiting_confirmation',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS restaurant_event_inquiries (
    id uuid PRIMARY KEY,
    name text NOT NULL,
    phone text NOT NULL,
    email text,
    event_type text NOT NULL,
    preferred_date date,
    guest_count integer NOT NULL,
    notes text,
    status text NOT NULL DEFAULT 'received',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS restaurant_menu_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS restaurant_menu_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES restaurant_menu_categories(id) ON DELETE RESTRICT,
    name text NOT NULL,
    description text,
    price_pkr integer NOT NULL CHECK (price_pkr >= 0),
    image_url text,
    is_featured boolean NOT NULL DEFAULT false,
    is_available boolean NOT NULL DEFAULT true,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0)
);

CREATE TABLE IF NOT EXISTS restaurant_delivery_areas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    delivery_fee_pkr integer NOT NULL CHECK (delivery_fee_pkr >= 0),
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0)
);

CREATE TABLE IF NOT EXISTS restaurant_orders (
    id uuid PRIMARY KEY,
    customer_name text NOT NULL,
    phone text NOT NULL,
    fulfillment_type text NOT NULL CHECK (fulfillment_type IN ('pickup', 'delivery')),
    delivery_address text,
    delivery_area text,
    delivery_area_id bigint REFERENCES restaurant_delivery_areas(id) ON DELETE SET NULL,
    payment_method text NOT NULL CHECK (payment_method IN ('cod', 'card')),
    order_status text NOT NULL DEFAULT 'awaiting_confirmation',
    payment_status text NOT NULL DEFAULT 'unpaid',
    subtotal_pkr integer NOT NULL CHECK (subtotal_pkr >= 0),
    delivery_fee_pkr integer CHECK (delivery_fee_pkr >= 0),
    total_pkr integer CHECK (total_pkr >= 0),
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE restaurant_orders
    ADD COLUMN IF NOT EXISTS delivery_area_id bigint
    REFERENCES restaurant_delivery_areas(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS restaurant_order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id uuid NOT NULL REFERENCES restaurant_orders(id) ON DELETE CASCADE,
    menu_item_id integer NOT NULL,
    item_name text NOT NULL,
    quantity integer NOT NULL CHECK (quantity BETWEEN 1 AND 20),
    unit_price_pkr integer NOT NULL CHECK (unit_price_pkr >= 0)
);

CREATE TABLE IF NOT EXISTS restaurant_order_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id uuid NOT NULL REFERENCES restaurant_orders(id) ON DELETE CASCADE,
    actor text NOT NULL,
    action text NOT NULL,
    previous_order_status text NOT NULL,
    new_order_status text NOT NULL,
    previous_payment_status text NOT NULL,
    new_payment_status text NOT NULL,
    previous_delivery_fee_pkr integer,
    new_delivery_fee_pkr integer,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS restaurant_order_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id uuid NOT NULL REFERENCES restaurant_orders(id) ON DELETE CASCADE,
    channel text NOT NULL CHECK (channel IN ('email', 'whatsapp')),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sending', 'sent')),
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    available_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_until timestamptz,
    last_error text,
    delivered_recipients jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at timestamptz,
    UNIQUE (order_id, channel)
);

ALTER TABLE restaurant_order_notifications
    ADD COLUMN IF NOT EXISTS delivered_recipients jsonb NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE restaurant_order_audit
    ADD COLUMN IF NOT EXISTS previous_delivery_fee_pkr integer;
ALTER TABLE restaurant_order_audit
    ADD COLUMN IF NOT EXISTS new_delivery_fee_pkr integer;

CREATE TABLE IF NOT EXISTS django_cache (
    cache_key varchar(255) PRIMARY KEY,
    value text NOT NULL,
    expires timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS django_cache_expires_idx
    ON django_cache (expires);

CREATE INDEX IF NOT EXISTS restaurant_orders_created_at_idx
    ON restaurant_orders (created_at DESC);
CREATE INDEX IF NOT EXISTS restaurant_order_items_order_id_idx
    ON restaurant_order_items (order_id);
CREATE INDEX IF NOT EXISTS restaurant_order_audit_order_id_idx
    ON restaurant_order_audit (order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS restaurant_order_notifications_ready_idx
    ON restaurant_order_notifications (status, available_at);
CREATE INDEX IF NOT EXISTS restaurant_menu_items_category_idx
    ON restaurant_menu_items (category_id, is_active, is_available, sort_order);
CREATE INDEX IF NOT EXISTS restaurant_delivery_areas_active_idx
    ON restaurant_delivery_areas (is_active, sort_order);
